### ISSUE TITLE
How to find your article?

### ISSUE THREAD

**Issue by yhykid** [sharma1256/cbf-constrained_ppo#1]
Hi,I am grateful to discover the repo but I cant find this article on Google.So how can I find the article?Thank you !!!

**Comment by sharma1256** [comment]
Hi there,  I'll be attaching the link to our paper in the next couple days and share that with you as well. Thank you.

**Comment by yhykid** [comment]
OK,thank you!

**Comment by sharma1256** [comment]
Please find the paper here: https://arxiv.org/abs/2403.04007 
@yhykid
